### ISSUE TITLE
 Attempt to run using other datasets

### ISSUE THREAD

**Issue by agleaner** [GrokCV/HazyDet#10]
When I tried running your algorithm using someone else's dataset, I encountered the following error:  
`FileNotFoundError: [Errno 2] No such file or directory: '/media/ST8000/hqt/HazyDet/HazyDet/Depth/normalized_depth_maps/0000072_05564_d_0000007.png'`.  
But I'm still using your depth dataset; I only replaced the train and val datasets. Could you please explain the possible cause of this issue? Additionally, if the annotation format of other datasets differs from yours, how should I modify it to make it compatible with your code?

**Comment by agleaner** [comment]
And I am using the JPG format instead of PNG.

**Comment by YimianDai** [comment]
From my understanding of your query, it appears that the issue you're encountering might not be directly related to the HazyDet codebase or dataset itself. Instead, it might be more related to adapting the code and adjusting it to fit your own dataset.

This adaptation process often involves making some modifications in the PyTorch and MMDetection framework. I understand that this process can be complex if you're not already familiar with these tools.

My recommendation would be to further deepen your understanding of both PyTorch and MMDetection to facilitate this adjustment process. The MMDetection community is an excellent resource for asking questions and seeking guidance. They have a wealth of knowledge and are generally very helpful in assisting with such issues.

**Comment by ironmanfcf** [comment]
There are too few error messages, I am unable to answer your question. But there is a path reading error. I suggest you debug the loadDualAnnotations class in loading.py and check if it correctly reads the depth map data. Additionally, I use PNG to store normalized relative depth values, which facilitates storage and visualization. However, during training, it is necessary to consider the maximum depth of each image.
You can modify the method of reading depth data in _loads_sg_map, so that different reading formats of depth data can be read.

**Comment by agleaner** [comment]
> 错误消息太少，我无法回答您的问题。但是存在路径读取错误。我建议您在 loading.py 中调试 loadDualAnnotations 类，并检查它是否正确读取深度图数据。此外，我使用 PNG 来存储标准化的相对深度值，这有助于存储和可视化。但是，在训练期间，有必要考虑每张图像的最大深度。您可以在 _loads_sg_map 中修改读取深度数据的方法，以便读取不同格式的深度数据。

I think the depth map data is read correctly, because it works fine when I use your train and val data, but the error appears when I use the visdrone dataset. The depth map data I use is still provided by you. I don't know if the format is incorrect when I convert the visdrone data annotation format from txt to json, so that the vis drone's train and val data cannot be read correctly.
