### ISSUE TITLE
是否可以用自己的数据集生成对应的仿真图象？

### ISSUE THREAD

**Issue by 733ly** [GrokCV/HazyDet#11]
另外我想问，这个检测器在实时性方面表现如何？

**Comment by 733ly** [comment]
请问你们尝试过直接对小目标进行检测的效果吗？我的意思是没有雾天的情况下，直接的无人机视角下小目标检测效果由这个深度信息会有改善吗？

**Comment by ironmanfcf** [comment]
This is a very meaningful question, as the main focus of our paper is on harsh environments, I did not publish experimental data without fog conditions.     
We have previously trained all models in the benchmark on data without fog, and found that models without simulation foggy will experience performance degradation in foggy conditions. However, we have not yet attempted the effect of small target detection without fog alone, and we may further explore it in the future.
