### ISSUE TITLE
How do you generate depth map on metricd3D?

### ISSUE THREAD

**Issue by agleaner** [GrokCV/HazyDet#13]
Which model did you use? Did you make any changes to its parameters?I look forward to your answer in your spare time.

**Comment by ironmanfcf** [comment]
I am using the giant2 version of metric3dV1, the download link is in the [huggingface](https://huggingface.co/JUGGHM/Metric3D/blob/main/metric_depth_vit_giant2_800k.pth). I suggest you check the user manual for [metric3D](https://github.com/YvanYin/Metric3D) on the official website for specific reasoning methods.   
I have also tried other versions of metric3dV2, but the results have not improved, and even some scenes have larger errors. I hope you can solve this problem in your future exploration.
