### ISSUE TITLE
图片文件显示已损坏

### ISSUE THREAD

**Issue by www948** [GrokCV/HazyDet#3]
你好，我下载了数据集 但打开的时候显示图片文件已损坏，重复了几次排除了下载时的网络问题 感谢回答，谢谢

**Comment by YimianDai** [comment]
我们又验证了一遍，是没问题的。

您能提供 您是百度云 还是 OneDrive 下载，具体哪个压缩包的图片损坏吗？

**Comment by legendary111** [comment]
我这里也是文件已损坏，所有的图片都是这样子，百度云下载的
onedrive的链接打不开？

**Comment by YimianDai** [comment]
我们发现了一个问题，可能是您把 MacOS 的隐藏文件当成正式图片了，而我在 MacOS 里看不到这些文件（隐藏了）

我们马上会更新一版不带这些隐藏文件的

**Comment by YimianDai** [comment]
上周百度云已经替换完成
