### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by cdzheng2g** [GrokCV/HazyDet#4]
Is the test performance index mAP in the paper experiment mAP50-95?

**Comment by ironmanfcf** [comment]
Yes, we used the default coco accuracy metric in mmdet, and the mAP mentioned in the paper is actually mAP50-95:0.05. I suggest you refer to the website for specific information: https://github.com/open-mmlab/mmdetection/blob/main/mmdet/evaluation/metrics/coco_metric.py.
