### ISSUE TITLE
运行报错求助

### ISSUE THREAD

**Issue by agleaner** [GrokCV/HazyDet#7]
作者你好！请问运行时出现这样的报错如何处理FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/private/fcf/Public_dataset/HazyDet-365K/data/HazyDet365K/train/train_coco.json'

**Comment by agleaner** [comment]
作者您好！非常感谢您的回复，在我解决完路径问题后尝试运行该项目时，我使用的同样是3090服务器，但是会报这个错误，请问如何解决。torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 402.00 MiB (GPU 0; 23.70 GiB total capacity; 20.80 GiB already allocated; 402.88 MiB free; 21.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ironmanfcf** [comment]
I haven't encountered this problem before, it may be due to slight differences in graphics cards, but I suggest you reduce the resolution of the input images during training, which can significantly reduce the memory usage.
